config/routes.rb
Rails.application.routes.draw do
  resources :perfil
  root 'welcome#index'
  # get 'especial' to:'pefil#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
	validates :name, presence: true
	validates :profession, presence: true
	validates :age, presence: true
	validates :age, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/perfil_controller.rb
class PerfilController < ApplicationController
  def index
  	@profiles = Profile.all
  end

  def show
  	@profile = Profile.find(params[:id])
  end

  def new
  	@profile = Profile.new
  end

  def create
  	@profile = Profile.new(perfil_params)
  	if @profile.save
  		redirect_to perfil_path(:id => @profile.id)
  	else
  		render :new
  	end
  end

  def edit
  	@profile = Profile.find(params[:id])
  end

  def update
  	@profile = Profile.find(params[:id])
  	if @profile.update(perfil_params)
  		redirect_to perfil_path(:id => @profile.id)
  	else
  		render :edit
  	end
  end

  def destroy
  	@profile = Profile.find(params[:id])
  	@profile.destroy
  	redirect_to perfil_index_path
  end

  private

  def perfil_params
  	params.require(:profile).permit(:name,:profession,:age)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/perfil_helper.rb
module PerfilHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prueba</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
	  <nav class="navbar navbar-default" role="navigation">
		<div class="navbar-header">
			<%= link_to "Prueba Rails", root_path, class: "navbar-brand"%>
		</div>
		<div>
			<ul class="nav navbar-nav">
				<li><%= link_to "Perfil", "/perfil"%></li>
			</ul>
		</div>
	  </nav>

	  <div class="container">
	    <%= yield %>
	  </div>
  </body>
</html>

app/views/perfil/_form.html.erb
<h1><%= name %> Perfil</h1><hr>
<%= form_for @profile,url:{action:accion} do |p|  %>
	<div class="form-group row <%if @profile.errors[:name].count>0 %> has-error <%end%>">
		<div class="col-md-3">
			<label class="control-label">Nombre: </label>
		</div>
		<div class="col-md-8">
			<%= p.text_field :name, class:"form-control" %>
		</div>
	</div>
	<%if @profile.errors[:name].count>0 %>
		<div class="alert alert-danger">
			<% @profile.errors[:name].each do |e| %>
  				<strong>Error!</strong> <%= e %>
  			<% end %>
		</div>
	<%end%>
	<div class="form-group row <%if @profile.errors[:profession].count>0 %> has-error <%end%>">
		<div class="col-md-3">
			<label class="control-label">Profesión: </label>
		</div>
		<div class="col-md-8">
			<%= p.text_field :profession, class:"form-control" %>
		</div>
	</div>
	<%if @profile.errors[:profession].count>0 %>
		<div class="alert alert-danger">
			<% @profile.errors[:profession].each do |e| %>
  				<strong>Error!</strong> <%= e %>
  			<% end %>
		</div>
	<%end%>
	<div class="form-group row <%if @profile.errors[:age].count>0 %> has-error <%end%>">
		<div class="col-md-3">
			<label class="control-label">Edad: </label>
		</div>
		<div class="col-md-8">
			<%= p.text_field :age, class:"form-control" %>
		</div>
	</div>
	<%if @profile.errors[:age].count>0 %>
		<div class="alert alert-danger">
			<% @profile.errors[:age].each do |e| %>
  				<strong>Error!</strong> <%= e %>
  			<% end %>
		</div>
	<%end%>
	<div class="form-group row">
		<%= p.submit "Guardar", class:"btn btn-success" %>
	</div>
<% end %>

app/views/perfil/edit.html.erb
<%= render "form", name:"Editar", accion:"update" %>

app/views/perfil/index.html.erb
<div class="row">
	<h1>Perfiles</h1>
	<%= link_to 'Crear nuevo Perfil', new_perfil_path ,class:'btn btn-success' %>
	<% @profiles.each do |p| %>
		<div class="panel panel-default">
			<div class="panel-body">
				<ul>
					<li><b>Nombre: </b><%= p.name %></li>
					<li><b>Profesión: </b><%= p.profession %></li>
					<li><b>Edad: </b><%= p.age %></li>
				<ul>
			</div>
			<div class="panel-footer">
				<%= link_to 'Ver', perfil_path(:id => p.id) ,class:'btn btn-info' %>
				<%= link_to 'Editar', edit_perfil_path(:id => p.id) ,class:'btn btn-success' %>
				<%= link_to 'Eliminar',url_for(action: :destroy,id: p.id),method: :delete, data: {confirm: "¿Deseas borrar este registro?"}, class:'btn btn-danger' %>
			</div>
		</div>
	<% end %>
</div>

app/views/perfil/new.html.erb
<%= render "form", name:"Crear", accion:"create" %>

app/views/perfil/show.html.erb
<div class="row">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h1>Perfil</h1>
		</div>
		<div class="panel-body">
			<p><b>Nombre: </b><%= @profile.name %></p>
		</div>
		<div class="panel-body">
			<p><b>Profesión: </b><%= @profile.profession %></p>
		</div>
		<div class="panel-body">
			<p><b>Edad: </b><%= @profile.age %></p>
		</div>
	</div>
	<%= link_to "Regresar", "/perfil", class:"btn btn-success" %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>